version: "2.4"

services:
  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"
  redis:
    image: "bitnami/redis:5.0.4"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"
  fastseo:
    build: ./fastseo
    command: "uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80"
    container_name: fastseo
    volumes:
      - ./fastseo/:/app/
    ports:
      - 80:80
  celery_worker:
    build: ./fastseo
    command: celery worker -A worker.celery_worker -l info -Q test-queue -c 1
    volumes:
      - ./fastseo/app/:/app/
    restart: on-failure
    environment:
      - timezone=Europe/London
  # beat:
  #   container_name: beat
  #   restart: unless-stopped
  #   build: ./fastseo
  #   command: ["celery", "beat", "-A", "worker.celery_worker",
  #             "-S", "redisbeat.RedisScheduler", "-l", "INFO"]
  #   volumes:
  #     - ./fastseo/app/:/app/
  #   depends_on:
  #     - celery_worker
  #     - redis
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - 8123:8123
volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local